<?php
/**
 * CustomerReturnsDlvryMaintenanceItemObjectListHeadersApi
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\CustomerReturnsDelivery
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Customer Returns Delivery (A2X)
 *
 * This synchronous inbound service enables you to read, create, update, and delete customer returns deliveries. It can be consumed in Fiori apps and on other user interfaces.
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BeLenka\SAP\CustomerReturnsDelivery\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use BeLenka\SAP\CustomerReturnsDelivery\ApiException;
use BeLenka\SAP\CustomerReturnsDelivery\Configuration;
use BeLenka\SAP\CustomerReturnsDelivery\HeaderSelector;
use BeLenka\SAP\CustomerReturnsDelivery\ObjectSerializer;

/**
 * CustomerReturnsDlvryMaintenanceItemObjectListHeadersApi Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\CustomerReturnsDelivery
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomerReturnsDlvryMaintenanceItemObjectListHeadersApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGet' => [
            'application/json',
        ],
        'aReturnsDeliverySrlNmbrMaintenanceItemObjectListToMaintenanceItemObjectGet' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGet
     *
     * Reads maintenance item object lists of specific customer returns delivery item.
     *
     * @param  string $delivery_document Delivery (required)
     * @param  string $delivery_document_item Item (required)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;63) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGet'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\CustomerReturnsDelivery\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \BeLenka\SAP\CustomerReturnsDelivery\Model\AReturnsDeliverySrlNmbrType|\BeLenka\SAP\CustomerReturnsDelivery\Model\Error
     */
    public function aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGet($delivery_document, $delivery_document_item, $select = null, $expand = null, string $contentType = self::contentTypes['aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGet'][0])
    {
        list($response) = $this->aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGetWithHttpInfo($delivery_document, $delivery_document_item, $select, $expand, $contentType);
        return $response;
    }

    /**
     * Operation aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGetWithHttpInfo
     *
     * Reads maintenance item object lists of specific customer returns delivery item.
     *
     * @param  string $delivery_document Delivery (required)
     * @param  string $delivery_document_item Item (required)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;63) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGet'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\CustomerReturnsDelivery\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \BeLenka\SAP\CustomerReturnsDelivery\Model\AReturnsDeliverySrlNmbrType|\BeLenka\SAP\CustomerReturnsDelivery\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGetWithHttpInfo($delivery_document, $delivery_document_item, $select = null, $expand = null, string $contentType = self::contentTypes['aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGet'][0])
    {
        $request = $this->aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGetRequest($delivery_document, $delivery_document_item, $select, $expand, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\BeLenka\SAP\CustomerReturnsDelivery\Model\AReturnsDeliverySrlNmbrType' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BeLenka\SAP\CustomerReturnsDelivery\Model\AReturnsDeliverySrlNmbrType' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\BeLenka\SAP\CustomerReturnsDelivery\Model\AReturnsDeliverySrlNmbrType', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                
            }

            $returnType = '\BeLenka\SAP\CustomerReturnsDelivery\Model\AReturnsDeliverySrlNmbrType';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BeLenka\SAP\CustomerReturnsDelivery\Model\AReturnsDeliverySrlNmbrType',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                
            }
            throw $e;
        }
    }

    /**
     * Operation aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGetAsync
     *
     * Reads maintenance item object lists of specific customer returns delivery item.
     *
     * @param  string $delivery_document Delivery (required)
     * @param  string $delivery_document_item Item (required)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;63) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGetAsync($delivery_document, $delivery_document_item, $select = null, $expand = null, string $contentType = self::contentTypes['aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGet'][0])
    {
        return $this->aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGetAsyncWithHttpInfo($delivery_document, $delivery_document_item, $select, $expand, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGetAsyncWithHttpInfo
     *
     * Reads maintenance item object lists of specific customer returns delivery item.
     *
     * @param  string $delivery_document Delivery (required)
     * @param  string $delivery_document_item Item (required)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;63) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGetAsyncWithHttpInfo($delivery_document, $delivery_document_item, $select = null, $expand = null, string $contentType = self::contentTypes['aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGet'][0])
    {
        $returnType = '\BeLenka\SAP\CustomerReturnsDelivery\Model\AReturnsDeliverySrlNmbrType';
        $request = $this->aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGetRequest($delivery_document, $delivery_document_item, $select, $expand, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGet'
     *
     * @param  string $delivery_document Delivery (required)
     * @param  string $delivery_document_item Item (required)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;63) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGetRequest($delivery_document, $delivery_document_item, $select = null, $expand = null, string $contentType = self::contentTypes['aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGet'][0])
    {

        // verify the required parameter 'delivery_document' is set
        if ($delivery_document === null || (is_array($delivery_document) && count($delivery_document) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $delivery_document when calling aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGet'
            );
        }
        if (strlen($delivery_document) > 10) {
            throw new \InvalidArgumentException('invalid length for "$delivery_document" when calling CustomerReturnsDlvryMaintenanceItemObjectListHeadersApi.aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGet, must be smaller than or equal to 10.');
        }
        
        // verify the required parameter 'delivery_document_item' is set
        if ($delivery_document_item === null || (is_array($delivery_document_item) && count($delivery_document_item) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $delivery_document_item when calling aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGet'
            );
        }
        if (strlen($delivery_document_item) > 6) {
            throw new \InvalidArgumentException('invalid length for "$delivery_document_item" when calling CustomerReturnsDlvryMaintenanceItemObjectListHeadersApi.aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGet, must be smaller than or equal to 6.');
        }
        
        
        

        $resourcePath = '/A_ReturnsDeliveryItem(DeliveryDocument=\'{DeliveryDocument}\',DeliveryDocumentItem=\'{DeliveryDocumentItem}\')/to_SerialDeliveryItem';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $select,
            '$select', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $expand,
            '$expand', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);


        // path params
        if ($delivery_document !== null) {
            $resourcePath = str_replace(
                '{' . 'DeliveryDocument' . '}',
                ObjectSerializer::toPathValue($delivery_document),
                $resourcePath
            );
        }
        // path params
        if ($delivery_document_item !== null) {
            $resourcePath = str_replace(
                '{' . 'DeliveryDocumentItem' . '}',
                ObjectSerializer::toPathValue($delivery_document_item),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation aReturnsDeliverySrlNmbrMaintenanceItemObjectListToMaintenanceItemObjectGet
     *
     * Reads maintenance item objects of specific customer returns delivery maintenance item object list.
     *
     * @param  string $maintenance_item_object_list Object list (required)
     * @param  string $filter Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)
     * @param  string $inlinecount Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aReturnsDeliverySrlNmbrMaintenanceItemObjectListToMaintenanceItemObjectGet'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\CustomerReturnsDelivery\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \BeLenka\SAP\CustomerReturnsDelivery\Model\Wrapper4|\BeLenka\SAP\CustomerReturnsDelivery\Model\Error
     */
    public function aReturnsDeliverySrlNmbrMaintenanceItemObjectListToMaintenanceItemObjectGet($maintenance_item_object_list, $filter = null, $inlinecount = null, $select = null, string $contentType = self::contentTypes['aReturnsDeliverySrlNmbrMaintenanceItemObjectListToMaintenanceItemObjectGet'][0])
    {
        list($response) = $this->aReturnsDeliverySrlNmbrMaintenanceItemObjectListToMaintenanceItemObjectGetWithHttpInfo($maintenance_item_object_list, $filter, $inlinecount, $select, $contentType);
        return $response;
    }

    /**
     * Operation aReturnsDeliverySrlNmbrMaintenanceItemObjectListToMaintenanceItemObjectGetWithHttpInfo
     *
     * Reads maintenance item objects of specific customer returns delivery maintenance item object list.
     *
     * @param  string $maintenance_item_object_list Object list (required)
     * @param  string $filter Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)
     * @param  string $inlinecount Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aReturnsDeliverySrlNmbrMaintenanceItemObjectListToMaintenanceItemObjectGet'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\CustomerReturnsDelivery\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \BeLenka\SAP\CustomerReturnsDelivery\Model\Wrapper4|\BeLenka\SAP\CustomerReturnsDelivery\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function aReturnsDeliverySrlNmbrMaintenanceItemObjectListToMaintenanceItemObjectGetWithHttpInfo($maintenance_item_object_list, $filter = null, $inlinecount = null, $select = null, string $contentType = self::contentTypes['aReturnsDeliverySrlNmbrMaintenanceItemObjectListToMaintenanceItemObjectGet'][0])
    {
        $request = $this->aReturnsDeliverySrlNmbrMaintenanceItemObjectListToMaintenanceItemObjectGetRequest($maintenance_item_object_list, $filter, $inlinecount, $select, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\BeLenka\SAP\CustomerReturnsDelivery\Model\Wrapper4' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BeLenka\SAP\CustomerReturnsDelivery\Model\Wrapper4' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\BeLenka\SAP\CustomerReturnsDelivery\Model\Wrapper4', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                
            }

            $returnType = '\BeLenka\SAP\CustomerReturnsDelivery\Model\Wrapper4';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BeLenka\SAP\CustomerReturnsDelivery\Model\Wrapper4',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                
            }
            throw $e;
        }
    }

    /**
     * Operation aReturnsDeliverySrlNmbrMaintenanceItemObjectListToMaintenanceItemObjectGetAsync
     *
     * Reads maintenance item objects of specific customer returns delivery maintenance item object list.
     *
     * @param  string $maintenance_item_object_list Object list (required)
     * @param  string $filter Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)
     * @param  string $inlinecount Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aReturnsDeliverySrlNmbrMaintenanceItemObjectListToMaintenanceItemObjectGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aReturnsDeliverySrlNmbrMaintenanceItemObjectListToMaintenanceItemObjectGetAsync($maintenance_item_object_list, $filter = null, $inlinecount = null, $select = null, string $contentType = self::contentTypes['aReturnsDeliverySrlNmbrMaintenanceItemObjectListToMaintenanceItemObjectGet'][0])
    {
        return $this->aReturnsDeliverySrlNmbrMaintenanceItemObjectListToMaintenanceItemObjectGetAsyncWithHttpInfo($maintenance_item_object_list, $filter, $inlinecount, $select, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation aReturnsDeliverySrlNmbrMaintenanceItemObjectListToMaintenanceItemObjectGetAsyncWithHttpInfo
     *
     * Reads maintenance item objects of specific customer returns delivery maintenance item object list.
     *
     * @param  string $maintenance_item_object_list Object list (required)
     * @param  string $filter Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)
     * @param  string $inlinecount Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aReturnsDeliverySrlNmbrMaintenanceItemObjectListToMaintenanceItemObjectGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aReturnsDeliverySrlNmbrMaintenanceItemObjectListToMaintenanceItemObjectGetAsyncWithHttpInfo($maintenance_item_object_list, $filter = null, $inlinecount = null, $select = null, string $contentType = self::contentTypes['aReturnsDeliverySrlNmbrMaintenanceItemObjectListToMaintenanceItemObjectGet'][0])
    {
        $returnType = '\BeLenka\SAP\CustomerReturnsDelivery\Model\Wrapper4';
        $request = $this->aReturnsDeliverySrlNmbrMaintenanceItemObjectListToMaintenanceItemObjectGetRequest($maintenance_item_object_list, $filter, $inlinecount, $select, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'aReturnsDeliverySrlNmbrMaintenanceItemObjectListToMaintenanceItemObjectGet'
     *
     * @param  string $maintenance_item_object_list Object list (required)
     * @param  string $filter Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)
     * @param  string $inlinecount Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aReturnsDeliverySrlNmbrMaintenanceItemObjectListToMaintenanceItemObjectGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function aReturnsDeliverySrlNmbrMaintenanceItemObjectListToMaintenanceItemObjectGetRequest($maintenance_item_object_list, $filter = null, $inlinecount = null, $select = null, string $contentType = self::contentTypes['aReturnsDeliverySrlNmbrMaintenanceItemObjectListToMaintenanceItemObjectGet'][0])
    {

        // verify the required parameter 'maintenance_item_object_list' is set
        if ($maintenance_item_object_list === null || (is_array($maintenance_item_object_list) && count($maintenance_item_object_list) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $maintenance_item_object_list when calling aReturnsDeliverySrlNmbrMaintenanceItemObjectListToMaintenanceItemObjectGet'
            );
        }



        

        $resourcePath = '/A_ReturnsDeliverySrlNmbr({MaintenanceItemObjectList})/to_MaintenanceItemObject';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter,
            '$filter', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $inlinecount,
            '$inlinecount', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $select,
            '$select', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);


        // path params
        if ($maintenance_item_object_list !== null) {
            $resourcePath = str_replace(
                '{' . 'MaintenanceItemObjectList' . '}',
                ObjectSerializer::toPathValue($maintenance_item_object_list),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
