<?php
/**
 * APICUSTOMERRETURNSDELIVERYSRVAReturnsDeliveryMaintObjTypeTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\CustomerReturnsDelivery
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Customer Returns Delivery (A2X)
 *
 * This synchronous inbound service enables you to read, create, update, and delete customer returns deliveries. It can be consumed in Fiori apps and on other user interfaces.
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace BeLenka\SAP\CustomerReturnsDelivery\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * APICUSTOMERRETURNSDELIVERYSRVAReturnsDeliveryMaintObjTypeTest Class Doc Comment
 *
 * @category    Class
 * @description APICUSTOMERRETURNSDELIVERYSRVAReturnsDeliveryMaintObjType
 * @package     BeLenka\SAP\CustomerReturnsDelivery
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class APICUSTOMERRETURNSDELIVERYSRVAReturnsDeliveryMaintObjTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "APICUSTOMERRETURNSDELIVERYSRVAReturnsDeliveryMaintObjType"
     */
    public function testAPICUSTOMERRETURNSDELIVERYSRVAReturnsDeliveryMaintObjType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "assembly"
     */
    public function testPropertyAssembly()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "equipment"
     */
    public function testPropertyEquipment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "functional_location"
     */
    public function testPropertyFunctionalLocation()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "maintenance_item_object"
     */
    public function testPropertyMaintenanceItemObject()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "maintenance_item_object_list"
     */
    public function testPropertyMaintenanceItemObjectList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "maintenance_notification"
     */
    public function testPropertyMaintenanceNotification()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "maint_object_loc_acct_assgmt_nmbr"
     */
    public function testPropertyMaintObjectLocAcctAssgmtNmbr()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "material"
     */
    public function testPropertyMaterial()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "serial_number"
     */
    public function testPropertySerialNumber()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
