<?php
/**
 * APICUSTOMERRETURNSDELIVERYSRVPutawayReportTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\CustomerReturnsDelivery
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Customer Returns Delivery (A2X)
 *
 * This synchronous inbound service enables you to read, create, update, and delete customer returns deliveries. It can be consumed in Fiori apps and on other user interfaces.
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace BeLenka\SAP\CustomerReturnsDelivery\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * APICUSTOMERRETURNSDELIVERYSRVPutawayReportTest Class Doc Comment
 *
 * @category    Class
 * @description APICUSTOMERRETURNSDELIVERYSRVPutawayReport
 * @package     BeLenka\SAP\CustomerReturnsDelivery
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class APICUSTOMERRETURNSDELIVERYSRVPutawayReportTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "APICUSTOMERRETURNSDELIVERYSRVPutawayReport"
     */
    public function testAPICUSTOMERRETURNSDELIVERYSRVPutawayReport()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "system_message_identification"
     */
    public function testPropertySystemMessageIdentification()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "system_message_number"
     */
    public function testPropertySystemMessageNumber()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "system_message_type"
     */
    public function testPropertySystemMessageType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "system_message_variable1"
     */
    public function testPropertySystemMessageVariable1()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "system_message_variable2"
     */
    public function testPropertySystemMessageVariable2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "system_message_variable3"
     */
    public function testPropertySystemMessageVariable3()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "system_message_variable4"
     */
    public function testPropertySystemMessageVariable4()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "batch"
     */
    public function testPropertyBatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "delivery_quantity_unit"
     */
    public function testPropertyDeliveryQuantityUnit()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "actual_delivery_quantity"
     */
    public function testPropertyActualDeliveryQuantity()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "delivery_document_item_text"
     */
    public function testPropertyDeliveryDocumentItemText()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "material"
     */
    public function testPropertyMaterial()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "delivery_document_item"
     */
    public function testPropertyDeliveryDocumentItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "delivery_document"
     */
    public function testPropertyDeliveryDocument()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
