<?php
/**
 * CustomerReturnsDeliveryHeadersApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\CustomerReturnsDelivery
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Customer Returns Delivery (A2X)
 *
 * This synchronous inbound service enables you to read, create, update, and delete customer returns deliveries. It can be consumed in Fiori apps and on other user interfaces.
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\CustomerReturnsDelivery\Test\Api;

use \BeLenka\SAP\CustomerReturnsDelivery\Configuration;
use \BeLenka\SAP\CustomerReturnsDelivery\ApiException;
use \BeLenka\SAP\CustomerReturnsDelivery\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CustomerReturnsDeliveryHeadersApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\CustomerReturnsDelivery
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomerReturnsDeliveryHeadersApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for aReturnsDeliveryHeaderDeliveryDocumentDelete
     *
     * Deletes customer returns deliveries..
     *
     */
    public function testAReturnsDeliveryHeaderDeliveryDocumentDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aReturnsDeliveryHeaderDeliveryDocumentGet
     *
     * Reads customer returns delivery headers..
     *
     */
    public function testAReturnsDeliveryHeaderDeliveryDocumentGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aReturnsDeliveryHeaderDeliveryDocumentPatch
     *
     * Updates customer returns delivery headers..
     *
     */
    public function testAReturnsDeliveryHeaderDeliveryDocumentPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aReturnsDeliveryHeaderDeliveryDocumentToDeliveryDocumentItemGet
     *
     * Reads items of specific customer returns delivery header..
     *
     */
    public function testAReturnsDeliveryHeaderDeliveryDocumentToDeliveryDocumentItemGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aReturnsDeliveryHeaderDeliveryDocumentToDeliveryDocumentPartnerGet
     *
     * Reads partners of specific customer returns delivery header..
     *
     */
    public function testAReturnsDeliveryHeaderDeliveryDocumentToDeliveryDocumentPartnerGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aReturnsDeliveryHeaderGet
     *
     * Reads customer returns delivery headers..
     *
     */
    public function testAReturnsDeliveryHeaderGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aReturnsDeliveryHeaderPost
     *
     * Creates customer returns deliveries with reference to preceding document..
     *
     */
    public function testAReturnsDeliveryHeaderPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for confirmPutawayAllItemsPost
     *
     * Confirms putaway quantity of customer returns delivery items..
     *
     */
    public function testConfirmPutawayAllItemsPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for confirmPutawayOneItemPost
     *
     * Confirms putaway quantity of customer returns delivery item..
     *
     */
    public function testConfirmPutawayOneItemPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postGoodsReceiptPost
     *
     * Posts goods receipt for customer returns delivery..
     *
     */
    public function testPostGoodsReceiptPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for putawayAllItemsPost
     *
     * Takes over delivery quantity as putaway quantity for all customer returns delivery items..
     *
     */
    public function testPutawayAllItemsPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for putawayOneItemPost
     *
     * Takes over delivery quantity as putaway quantity for specified customer returns delivery item..
     *
     */
    public function testPutawayOneItemPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for putawayOneItemWithBaseQuantityPost
     *
     * Sets putaway quantity and delivery quantity for customer returns delivery item..
     *
     */
    public function testPutawayOneItemWithBaseQuantityPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for putawayOneItemWithSalesQuantityPost
     *
     * Sets putaway quantity and delivery quantity for customer returns delivery item..
     *
     */
    public function testPutawayOneItemWithSalesQuantityPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reverseGoodsReceiptPost
     *
     * Reverses goods receipt for customer returns delivery..
     *
     */
    public function testReverseGoodsReceiptPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setPutawayQuantityWithBaseQuantityPost
     *
     * Sets putaway quantity in base unit of measure for delivery item..
     *
     */
    public function testSetPutawayQuantityWithBaseQuantityPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
