<?php
/**
 * CustomerReturnsDlvryMaintenanceItemObjectListHeadersApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\CustomerReturnsDelivery
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Customer Returns Delivery (A2X)
 *
 * This synchronous inbound service enables you to read, create, update, and delete customer returns deliveries. It can be consumed in Fiori apps and on other user interfaces.
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\CustomerReturnsDelivery\Test\Api;

use \BeLenka\SAP\CustomerReturnsDelivery\Configuration;
use \BeLenka\SAP\CustomerReturnsDelivery\ApiException;
use \BeLenka\SAP\CustomerReturnsDelivery\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CustomerReturnsDlvryMaintenanceItemObjectListHeadersApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\CustomerReturnsDelivery
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomerReturnsDlvryMaintenanceItemObjectListHeadersApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for aReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGet
     *
     * Reads maintenance item object lists of specific customer returns delivery item..
     *
     */
    public function testAReturnsDeliveryItemDeliveryDocumentDeliveryDocumentDeliveryDocumentItemDeliveryDocumentItemToSerialDeliveryItemGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aReturnsDeliverySrlNmbrMaintenanceItemObjectListToMaintenanceItemObjectGet
     *
     * Reads maintenance item objects of specific customer returns delivery maintenance item object list..
     *
     */
    public function testAReturnsDeliverySrlNmbrMaintenanceItemObjectListToMaintenanceItemObjectGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
